"""
WASI HTTP Handler Implementation

This module implements the wasi:http/incoming-handler interface for Python.
It provides a simple, Pythonic interface for handling HTTP requests.
"""

# These imports are generated by componentize-py from the WIT definitions
from http_handler import exports
from http_handler.imports import types
from http_handler.types import Ok

# Try to import the user's app module
try:
    import app
    USER_HANDLER = getattr(app, "handler", None)
except ImportError:
    USER_HANDLER = None


class IncomingHandler(exports.IncomingHandler):
    """
    HTTP request handler that bridges WASI HTTP to user Python code.

    This class:
    1. Receives WASI HTTP requests
    2. Converts them to simple Python dicts
    3. Calls the user's handler function
    4. Converts the response back to WASI HTTP format
    """

    def handle(self, request: types.IncomingRequest, response_out: types.ResponseOutparam):
        """Handle an incoming HTTP request."""
        # Convert WASI request to simple Python dict
        py_request = self._convert_request(request)

        # Call user handler or default handler
        if USER_HANDLER is not None:
            py_response = USER_HANDLER(py_request)
        else:
            py_response = self._default_handler(py_request)

        # Convert Python response back to WASI HTTP
        self._send_response(py_response, response_out)

    def _convert_request(self, request: types.IncomingRequest) -> dict:
        """Convert WASI HTTP request to Python dict."""
        path = request.path_with_query() or "/"

        # Parse path and query string
        if "?" in path:
            path_only, query_string = path.split("?", 1)
            query = self._parse_query_string(query_string)
        else:
            path_only = path
            query = {}

        return {
            "method": str(request.method()),
            "path": path_only,
            "query": query,
            "headers": {},  # TODO: Convert headers
        }

    def _parse_query_string(self, query_string: str) -> dict:
        """Parse query string into dict."""
        result = {}
        for pair in query_string.split("&"):
            if "=" in pair:
                key, value = pair.split("=", 1)
                # Basic URL decoding
                value = value.replace("%20", " ").replace("+", " ")
                result[key] = value
        return result

    def _default_handler(self, request: dict) -> dict:
        """Default handler when no user handler is provided."""
        path = request.get("path", "/")

        if path == "/" or path == "":
            return {
                "status": 200,
                "headers": {"content-type": "text/plain"},
                "body": "Fabricks Python Runtime v3.12.0\n\nNo handler configured.",
            }
        elif path == "/health":
            return {
                "status": 200,
                "headers": {"content-type": "text/plain"},
                "body": "OK",
            }
        else:
            return {
                "status": 404,
                "headers": {"content-type": "text/plain"},
                "body": f"Not Found: {path}",
            }

    def _send_response(self, py_response: dict, response_out: types.ResponseOutparam):
        """Convert Python response to WASI HTTP and send it."""
        status = py_response.get("status", 200)
        headers_dict = py_response.get("headers", {})
        body = py_response.get("body", "")

        # Build headers
        headers = types.Fields()
        for name, value in headers_dict.items():
            if isinstance(value, str):
                value = value.encode("utf-8")
            headers.append(types.FieldEntry(name, value))

        # Create response
        response = types.OutgoingResponse(headers)
        response.set_status_code(status)

        # Write body
        body_handle = response.body()
        stream = body_handle.write()

        if isinstance(body, str):
            body = body.encode("utf-8")
        stream.blocking_write_and_flush(body)

        # Finish
        types.OutgoingBody.finish(body_handle, None)
        types.ResponseOutparam.set(response_out, Ok(response))
