"""
Fabricks Python Runtime - WASI HTTP Handler

This runtime implements the wasi:http/incoming-handler interface and loads
user Python code from /app at runtime via WASI filesystem preopens.

Users don't need to compile their Python to WASM - they just write Python
and this runtime executes it.

## How It Works

1. At startup, /app is added to sys.path
2. The runtime reads the entrypoint from /app/.fabricks.toml (or uses default)
3. User's module is imported dynamically
4. HTTP requests are bridged to the user's handler function

## User Handler Interface

Users implement a simple handler function:

    def handler(request):
        return {
            "status": 200,
            "headers": {"content-type": "text/plain"},
            "body": "Hello, World!"
        }
"""

import sys
import os
import importlib

# These imports are generated by componentize-py from the WIT definitions
from http_handler import exports
from http_handler.imports import types
from componentize_py_types import Ok

# Configuration
APP_DIR = "/app"
DEFAULT_MODULE = "app"
DEFAULT_HANDLER = "handler"

# Add app directory to Python path
if APP_DIR not in sys.path:
    sys.path.insert(0, APP_DIR)


def _load_entrypoint():
    """
    Load the entrypoint configuration.

    Reads from /app/.fabricks.toml if present, otherwise uses defaults.
    Returns (module_name, handler_name) tuple.
    """
    config_path = os.path.join(APP_DIR, ".fabricks.toml")

    module_name = DEFAULT_MODULE
    handler_name = DEFAULT_HANDLER

    # Try to read config file
    try:
        if os.path.exists(config_path):
            with open(config_path, "r") as f:
                content = f.read()
                # Simple TOML parsing for entrypoint
                for line in content.split("\n"):
                    line = line.strip()
                    if line.startswith("entrypoint"):
                        # Parse: entrypoint = "module:handler"
                        _, _, value = line.partition("=")
                        value = value.strip().strip('"').strip("'")
                        if ":" in value:
                            module_name, handler_name = value.split(":", 1)
                        else:
                            module_name = value
    except Exception:
        pass  # Use defaults on any error

    return module_name, handler_name


def _load_user_handler():
    """
    Dynamically load the user's handler function.

    Uses exec() instead of importlib to work with WASI filesystem preopens.
    Returns the handler function, or None if not found.
    """
    module_name, handler_name = _load_entrypoint()

    try:
        # Check if the module file exists
        module_path = os.path.join(APP_DIR, f"{module_name}.py")

        if not os.path.exists(module_path):
            # Try package style
            package_path = os.path.join(APP_DIR, module_name, "__init__.py")
            if os.path.exists(package_path):
                module_path = package_path
            else:
                print(f"Warning: User module not found at {module_path}")
                return None

        # Read and execute the module code
        # Using exec() instead of import_module to work with WASI preopens
        with open(module_path, "r") as f:
            code = f.read()

        # Create a namespace for the module
        module_globals = {"__name__": module_name, "__file__": module_path}
        exec(code, module_globals)  # noqa: S102

        # Get the handler function
        handler_func = module_globals.get(handler_name)

        if handler_func is None:
            print(f"Warning: Handler '{handler_name}' not found in module '{module_name}'")
            return None

        if not callable(handler_func):
            print(f"Warning: '{handler_name}' is not callable")
            return None

        return handler_func

    except FileNotFoundError as e:
        print(f"Warning: Could not read user module '{module_name}': {e}")
        return None
    except Exception as e:
        print(f"Warning: Error loading user handler: {e}")
        return None


# Load user handler at module init (after preopens are set up)
USER_HANDLER = None
_handler_loaded = False


def _ensure_handler_loaded():
    """Lazily load the user handler on first request."""
    global USER_HANDLER, _handler_loaded
    if not _handler_loaded:
        USER_HANDLER = _load_user_handler()
        _handler_loaded = True


class IncomingHandler(exports.IncomingHandler):
    """
    HTTP request handler that bridges WASI HTTP to user Python code.

    This class:
    1. Receives WASI HTTP requests
    2. Converts them to simple Python dicts
    3. Calls the user's handler function
    4. Converts the response back to WASI HTTP format
    """

    def handle(self, request: types.IncomingRequest, response_out: types.ResponseOutparam):
        """Handle an incoming HTTP request."""
        # Ensure user handler is loaded
        _ensure_handler_loaded()

        # Convert WASI request to simple Python dict
        py_request = self._convert_request(request)

        # Call user handler or default handler
        if USER_HANDLER is not None:
            try:
                py_response = USER_HANDLER(py_request)
            except Exception as e:
                py_response = {
                    "status": 500,
                    "headers": {"content-type": "text/plain"},
                    "body": f"Handler error: {e}",
                }
        else:
            py_response = self._default_handler(py_request)

        # Convert Python response back to WASI HTTP
        self._send_response(py_response, response_out)

    def _convert_request(self, request: types.IncomingRequest) -> dict:
        """Convert WASI HTTP request to Python dict."""
        path = request.path_with_query() or "/"

        # Parse path and query string
        if "?" in path:
            path_only, query_string = path.split("?", 1)
            query = self._parse_query_string(query_string)
        else:
            path_only = path
            query = {}

        # Get method as string
        method = str(request.method())

        return {
            "method": method,
            "path": path_only,
            "query": query,
            "headers": {},  # TODO: Convert headers from WASI types
        }

    def _parse_query_string(self, query_string: str) -> dict:
        """Parse query string into dict."""
        result = {}
        for pair in query_string.split("&"):
            if "=" in pair:
                key, value = pair.split("=", 1)
                # Basic URL decoding
                value = value.replace("%20", " ").replace("+", " ")
                result[key] = value
        return result

    def _default_handler(self, request: dict) -> dict:
        """Default handler when no user handler is found."""
        path = request.get("path", "/")

        if path == "/" or path == "":
            return {
                "status": 200,
                "headers": {"content-type": "text/plain"},
                "body": (
                    "Fabricks Python Runtime v3.12\n\n"
                    "No user handler found.\n\n"
                    "Create /app/app.py with a handler function:\n\n"
                    "    def handler(request):\n"
                    "        return {\n"
                    '            "status": 200,\n'
                    '            "body": "Hello!"\n'
                    "        }\n"
                ),
            }
        elif path == "/health":
            return {
                "status": 200,
                "headers": {"content-type": "text/plain"},
                "body": "OK",
            }
        else:
            return {
                "status": 404,
                "headers": {"content-type": "text/plain"},
                "body": f"Not Found: {path}",
            }

    def _send_response(self, py_response: dict, response_out: types.ResponseOutparam):
        """Convert Python response to WASI HTTP and send it."""
        status = py_response.get("status", 200)
        headers_dict = py_response.get("headers", {})
        body = py_response.get("body", "")

        # Build headers using from_list static method
        # WASI HTTP fields expect list of (name, value) tuples where value is bytes
        header_entries = []
        for name, value in headers_dict.items():
            if isinstance(value, str):
                value = value.encode("utf-8")
            header_entries.append((name, value))

        # Create headers from list - raises on error, returns Fields directly
        headers = types.Fields.from_list(header_entries)

        # Create response
        response = types.OutgoingResponse(headers)
        response.set_status_code(status)

        # Write body - must use context manager to properly drop stream before finish
        body_handle = response.body()
        with body_handle.write() as stream:
            if isinstance(body, str):
                body = body.encode("utf-8")
            stream.blocking_write_and_flush(body)

        # Finish - stream must be dropped before this call
        types.OutgoingBody.finish(body_handle, None)
        types.ResponseOutparam.set(response_out, Ok(response))
