//! Python builder using componentize-py.
//!
//! Builds Python projects to WebAssembly components using `componentize-py`.
//! This bundles the `CPython` interpreter with the user's Python code.
//!
//! ## Requirements
//!
//! - Python 3.10 or later
//! - componentize-py (`pip install componentize-py`)
//!
//! ## How It Works
//!
//! 1. Creates a build directory with the Fabricks Python runtime framework
//! 2. Copies the user's Python handler code
//! 3. Runs componentize-py to bundle `CPython` + framework + user code
//! 4. Produces a WASM component that handles HTTP requests
//!
//! ## User Experience
//!
//! Users write a simple handler function:
//!
//! ```python
//! def handler(request):
//!     return {"status": 200, "body": "Hello!"}
//! ```
//!
//! The builder wraps this with the WASI HTTP framework automatically.

use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result, bail};
use tracing::{debug, info};

use super::{BuildOutput, Builder, BuilderConfig};

/// Embedded Python runtime framework that bridges WASI HTTP to user handlers.
const RUNTIME_HANDLER_PY: &str = r#"
"""
WASI HTTP Handler Implementation

This module implements the wasi:http/incoming-handler interface for Python.
It provides a simple, Pythonic interface for handling HTTP requests.
"""

# These imports are generated by componentize-py from the WIT definitions
from http_handler import exports
from http_handler.imports import types
from http_handler.types import Ok

# Try to import the user's app module
try:
    import app
    USER_HANDLER = getattr(app, "handler", None)
except ImportError:
    USER_HANDLER = None


class IncomingHandler(exports.IncomingHandler):
    """
    HTTP request handler that bridges WASI HTTP to user Python code.

    This class:
    1. Receives WASI HTTP requests
    2. Converts them to simple Python dicts
    3. Calls the user's handler function
    4. Converts the response back to WASI HTTP format
    """

    def handle(self, request: types.IncomingRequest, response_out: types.ResponseOutparam):
        """Handle an incoming HTTP request."""
        # Convert WASI request to simple Python dict
        py_request = self._convert_request(request)

        # Call user handler or default handler
        if USER_HANDLER is not None:
            py_response = USER_HANDLER(py_request)
        else:
            py_response = self._default_handler(py_request)

        # Convert Python response back to WASI HTTP
        self._send_response(py_response, response_out)

    def _convert_request(self, request: types.IncomingRequest) -> dict:
        """Convert WASI HTTP request to Python dict."""
        path = request.path_with_query() or "/"

        # Parse path and query string
        if "?" in path:
            path_only, query_string = path.split("?", 1)
            query = self._parse_query_string(query_string)
        else:
            path_only = path
            query = {}

        return {
            "method": str(request.method()),
            "path": path_only,
            "query": query,
            "headers": {},  # TODO: Convert headers
        }

    def _parse_query_string(self, query_string: str) -> dict:
        """Parse query string into dict."""
        result = {}
        for pair in query_string.split("&"):
            if "=" in pair:
                key, value = pair.split("=", 1)
                # Basic URL decoding
                value = value.replace("%20", " ").replace("+", " ")
                result[key] = value
        return result

    def _default_handler(self, request: dict) -> dict:
        """Default handler when no user handler is provided."""
        path = request.get("path", "/")

        if path == "/" or path == "":
            return {
                "status": 200,
                "headers": {"content-type": "text/plain"},
                "body": "Fabricks Python Runtime\n\nNo handler configured.",
            }
        elif path == "/health":
            return {
                "status": 200,
                "headers": {"content-type": "text/plain"},
                "body": "OK",
            }
        else:
            return {
                "status": 404,
                "headers": {"content-type": "text/plain"},
                "body": f"Not Found: {path}",
            }

    def _send_response(self, py_response: dict, response_out: types.ResponseOutparam):
        """Convert Python response to WASI HTTP and send it."""
        status = py_response.get("status", 200)
        headers_dict = py_response.get("headers", {})
        body = py_response.get("body", "")

        # Build headers
        headers = types.Fields()
        for name, value in headers_dict.items():
            if isinstance(value, str):
                value = value.encode("utf-8")
            headers.append(types.FieldEntry(name, value))

        # Create response
        response = types.OutgoingResponse(headers)
        response.set_status_code(status)

        # Write body
        body_handle = response.body()
        stream = body_handle.write()

        if isinstance(body, str):
            body = body.encode("utf-8")
        stream.blocking_write_and_flush(body)

        # Finish
        types.OutgoingBody.finish(body_handle, None)
        types.ResponseOutparam.set(response_out, Ok(response))
"#;

/// Builder for Python projects.
pub struct PythonBuilder;

impl Builder for PythonBuilder {
    fn check_toolchain(&self) -> Result<()> {
        // Check for Python 3.10+
        let python_output = Command::new("python3").arg("--version").output();

        match python_output {
            Ok(output) if output.status.success() => {
                let version_str = String::from_utf8_lossy(&output.stdout);
                debug!("Found Python: {}", version_str.trim());

                // Parse version to check >= 3.10
                if let Some(version) = parse_python_version(&version_str)
                    && version < (3, 10)
                {
                    bail!(
                        "Python 3.10 or later is required, found {}.{}\n\n\
                         Please upgrade Python: https://www.python.org/downloads/",
                        version.0,
                        version.1
                    );
                }
            }
            _ => {
                bail!(
                    "Python 3 not found.\n\n\
                     Install Python 3.10+: https://www.python.org/downloads/"
                );
            }
        }

        // Check for componentize-py
        let comp_output = Command::new("componentize-py").arg("--version").output();

        match comp_output {
            Ok(output) if output.status.success() => {
                let version = String::from_utf8_lossy(&output.stdout);
                debug!("Found componentize-py: {}", version.trim());
                Ok(())
            }
            _ => {
                bail!(
                    "componentize-py not found.\n\n\
                     Install it with: pip install componentize-py\n\
                     Documentation: https://github.com/bytecodealliance/componentize-py"
                );
            }
        }
    }

    fn build(&self, config: &BuilderConfig<'_>) -> Result<BuildOutput> {
        info!("Building Python project with componentize-py");

        // Determine source directory and entrypoint
        let source = config.fabrickfile.source.as_ref().ok_or_else(|| {
            anyhow::anyhow!(
                "Python builds require a [source] section with path and entrypoint.\n\n\
                 Example:\n\
                 [source]\n\
                 path = \".\"\n\
                 entrypoint = \"app:handler\""
            )
        })?;

        let entrypoint = source.entrypoint.as_ref().ok_or_else(|| {
            anyhow::anyhow!(
                "Python builds require an entrypoint in [source].\n\n\
                 Example:\n\
                 [source]\n\
                 path = \".\"\n\
                 entrypoint = \"app:handler\"\n\n\
                 The entrypoint format is 'module:function' or 'module:Class'"
            )
        })?;

        let source_path = config.workdir.join(&source.path);

        // Parse entrypoint to get module and function name
        let (module_name, _handler_name) = parse_entrypoint(entrypoint)?;

        // Create a temp build directory to combine runtime framework with user code
        let build_dir = tempfile::tempdir().context("Failed to create temp build directory")?;
        let build_path = build_dir.path();

        debug!("Build directory: {}", build_path.display());

        // Write the runtime handler framework
        let handler_path = build_path.join("handler.py");
        std::fs::write(&handler_path, RUNTIME_HANDLER_PY)
            .context("Failed to write runtime handler")?;

        // Copy user's module to build directory
        copy_user_module(&source_path, build_path, module_name)?;

        // Create WIT directory with WASI HTTP bindings
        let wit_dir = build_path.join("wit");
        std::fs::create_dir_all(&wit_dir).context("Failed to create wit directory")?;
        create_http_handler_wit(&wit_dir, &config.fabrickfile.info.name)?;

        // Output path (in the original source directory, not temp)
        let output_name = format!("{}.wasm", config.fabrickfile.info.name.replace('-', "_"));
        let output_path = source_path.join(&output_name);

        // Build with componentize-py
        // We build the handler module which imports the user's app
        let mut cmd = Command::new("componentize-py");
        cmd.args([
            "--wit-path",
            "wit",
            "--world",
            "http-handler",
            "componentize",
            "handler", // The runtime framework is the entry point
            "-o",
        ])
        .arg(&output_path)
        .current_dir(build_path);

        debug!(
            "Running: componentize-py --wit-path wit --world http-handler componentize handler -o {}",
            output_path.display()
        );

        let output = cmd.output().context("Failed to execute componentize-py")?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let stdout = String::from_utf8_lossy(&output.stdout);
            bail!(
                "Python build failed:\n\nstdout:\n{stdout}\n\nstderr:\n{stderr}"
            );
        }

        let wasm_size = std::fs::metadata(&output_path)
            .context("Failed to get WASM file size")?
            .len();

        info!("Built {} ({wasm_size} bytes)", output_path.display());

        Ok(BuildOutput {
            wasm_path: output_path,
        })
    }
}

/// Parse entrypoint like "app:handler" into (module, function).
fn parse_entrypoint(entrypoint: &str) -> Result<(&str, &str)> {
    let parts: Vec<&str> = entrypoint.split(':').collect();
    if parts.len() != 2 {
        bail!(
            "Invalid entrypoint format: '{entrypoint}'\n\
             Expected 'module:function', e.g., 'app:handler'"
        );
    }
    Ok((parts[0], parts[1]))
}

/// Copy user's Python module to the build directory.
fn copy_user_module(source_path: &Path, build_path: &Path, module_name: &str) -> Result<()> {
    // The module can be either a single .py file or a package directory
    let py_file = source_path.join(format!("{module_name}.py"));
    let package_dir = source_path.join(module_name);

    if py_file.exists() {
        // Single file module - copy as app.py (the runtime expects 'app' module)
        let dest = build_path.join("app.py");
        std::fs::copy(&py_file, &dest).with_context(|| {
            format!("Failed to copy {} to build directory", py_file.display())
        })?;
        debug!("Copied {} -> {}", py_file.display(), dest.display());
    } else if package_dir.exists() && package_dir.is_dir() {
        // Package directory - copy as 'app' package
        let dest = build_path.join("app");
        copy_dir_recursive(&package_dir, &dest)?;
        debug!(
            "Copied package {} -> {}",
            package_dir.display(),
            dest.display()
        );
    } else {
        bail!(
            "Could not find Python module '{module_name}'.\n\
             Expected either:\n\
             - {}.py\n\
             - {}/ (directory with __init__.py)",
            py_file.display(),
            package_dir.display()
        );
    }

    Ok(())
}

/// Recursively copy a directory.
fn copy_dir_recursive(src: &Path, dst: &Path) -> Result<()> {
    std::fs::create_dir_all(dst)?;

    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let path = entry.path();
        let dest_path = dst.join(entry.file_name());

        if path.is_dir() {
            copy_dir_recursive(&path, &dest_path)?;
        } else {
            std::fs::copy(&path, &dest_path)?;
        }
    }

    Ok(())
}

/// Parse Python version string like "Python 3.12.0" into (major, minor).
fn parse_python_version(version_str: &str) -> Option<(u32, u32)> {
    let parts: Vec<&str> = version_str.split_whitespace().collect();
    if parts.len() >= 2 {
        let version_parts: Vec<&str> = parts[1].split('.').collect();
        if version_parts.len() >= 2 {
            let major = version_parts[0].parse().ok()?;
            let minor = version_parts[1].parse().ok()?;
            return Some((major, minor));
        }
    }
    None
}

/// Create the WIT file for HTTP handler interface.
fn create_http_handler_wit(wit_dir: &Path, package_name: &str) -> Result<()> {
    // WIT package names use kebab-case, so we keep dashes
    let wit_content = format!(
        r"// Auto-generated HTTP handler world for Fabricks Python app
// This defines the interface your Python code must implement.

package fabricks:{package_name}@1.0.0;

world http-handler {{
    // Import and export WASI HTTP proxy interfaces
    include wasi:http/proxy@0.2.0;
}}
"
    );

    let wit_path = wit_dir.join("world.wit");
    std::fs::write(&wit_path, wit_content).context("Failed to write WIT file")?;

    debug!("Created WIT file at {}", wit_path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_python_version() {
        assert_eq!(parse_python_version("Python 3.12.0"), Some((3, 12)));
        assert_eq!(parse_python_version("Python 3.10.5"), Some((3, 10)));
        assert_eq!(parse_python_version("Python 2.7.18"), Some((2, 7)));
        assert_eq!(parse_python_version("invalid"), None);
    }
}
